### ISSUE TITLE
Uniting the Isles ID:45727

### ISSUE THREAD

**Issue by OitzahBarsana** [Evolution-WoW/Bug-Report#1094]
Khadgar (inside the violet citadel) doesn't provide the quest Uniting the Isles.

![image](https://user-images.githubusercontent.com/104162698/168169834-c7fab961-ac95-4957-8d8a-0d9a05bba493.png)

**Comment by arft1kwerg** [comment]
Adding some info regarding how World Quests used to be unlocked on retail:

Before patch 7.1: Reaching lvl 110 would automatically give the player "Uniting the Isles" (id:43341) where the player has to reach Friendly with the following factions: Nightfallen, Court of Farondis, Highmountain, Dreamweavers, and Valajar.

After Patch 7.1.0 (2016-10-25): Same thing applies as above. However, if the player has already completed the quest "Uniting the Isles" (43341) on another character on their account, would be given "Uniting the Isles" (45727) instead. The latter quest just requiring the player to talk to Khadgar.

For both quests, if the player couldn't receive the respective quests due to a full quest log or similar. The quest could be picked up from Khadgar at the Violet Citadel instead.

**Comment by Denimz92** [comment]
You need to be at least Friendly reputation with each of the main Legion story factions before that quest will show up, recheck.

**Comment by arft1kwerg** [comment]
> You need to be at least Friendly reputation with each of the main Legion story factions before that quest will show up, recheck.

There is a known issue where "Uniting the Isles" (45727) doesn't show up at all. Have had to have GMs manually add the quest to 3 characters because it wasn't being offered despite fulfilling requirements. As for "Uniting the Isles" (43341) it could be picked up from Khadgar about 1-2 weeks ago however, it seems like some fix since then has made Khadgar unable to offer the quest. Check the discord for more info.

**Comment by Ragelezz** [comment]
if you don't see the quest at khadghar but you are level 110, relog and it will appear into your log

**Comment by arft1kwerg** [comment]
https://user-images.githubusercontent.com/29517963/168798036-45244f4e-adce-49dc-8506-04719a3a62e8.mp4
