### ISSUE TITLE
[Quest] warrior class hall campaign

### ISSUE THREAD

**Issue by Harakyri** [Evolution-WoW/Bug-Report#844]
Current behavior: Quest (42815) needs to temp spawn these NPC's (depending on player faction)
A side: 108973, vehicle doesn't work, spawns extra adds instead
H side: 100519, spawns extra adds

 Return to the Broken Shore 38904 - wrong scenario see https://www.youtube.com/watch?v=QrbX7JFaMmY 
After finishing the last stage of the scenario Danica the Reclaimer 93823 should teleport you from the scenario straight in the warrior class hall in order to complete the quest 

I will stop here for a few hours due to cant continue the class hall campaign without beeing in the skyhold . Gonna continue after
                     

How it should work:

Proof (video or image):

**Comment by Ragelezz** [comment]
https://github.com/Evolution-WoW/Bug-Report/issues/878
https://github.com/Evolution-WoW/Bug-Report/issues/877
https://github.com/Evolution-WoW/Bug-Report/issues/876

**Comment by FiuryMan** [comment]
>Current behavior: Quest (42815) needs to temp spawn these NPC's (depending on player faction)
A side: 108973, vehicle doesn't work, spawns extra adds instead
H side: 100519, spawns extra adds

Return to the Broken Shore 38904 - wrong scenario see https://www.youtube.com/watch?v=QrbX7JFaMmY
After finishing the last stage of the scenario Danica the Reclaimer 93823 should teleport you from the scenario straight in the warrior class hall in order to complete the quest

Set quest as Auto-Complete and on quest accept you get teleported to skyhold.
