### ISSUE TITLE
[Val'Sharah Storyline]

### ISSUE THREAD

**Issue by Infinity19o** [Evolution-WoW/Bug-Report#848]
**_Storyline Intro_**
Quest - **Cenarius, Keeper of the Grove** - https://www.wowhead.com/quest=40122/cenarius-keeper-of-the-grove
Cannot complete the quest.
Proof:
https://imgur.com/b2VjFjV
Due to this issue cannot continue the continues quest.
Which is:
https://www.wowhead.com/quest=38384/natures-call

**_Storyline Archdruid of Lore:_**
https://www.wowhead.com/quest=38381/archdruid-of-lore
The NPC does not give you starting quets. 
Due to this issue the whole storyline is affected.
Proof:
https://imgur.com/wBU8ZEM

**_Storyline Archdruid of the Claw:_**
https://www.wowhead.com/quest=38142/archdruid-of-the-claw
The NPC does not give you the quest. 
The whole storyline is affected due to this issue. 
Proof:
https://imgur.com/wBU8ZEM

**_Storyline Archdruid of the Vale:_**
https://www.wowhead.com/quest=38382/archdruid-of-the-vale
The NPC does not give the quest. 
The whole storyline afected due to this issue.
Proof:
https://imgur.com/wBU8ZEM

**Due to the Archdruid issues above cannot do/complete Into the Nightmare**
**Due to the Into the Nightmare issue cannot do/complete All Nightmare Long**

**_Storyline Bradensbrook:_**
Missing quest https://www.wowhead.com/quest=38644/the-farmsteads
Can continue the questline from the quest **Children of the Night** - https://www.wowhead.com/quest=38645/children-of-the-night
Proof:
https://imgur.com/oLWosQx
After completing the quest Children of the Night the NPC does not give you the next quest.
Which is **A Sight For Sore Eyes** - https://www.wowhead.com/quest=38646/a-sight-for-sore-eyes
Proof: 
https://imgur.com/VzVttur
Due to this issue cannot continue quest **For the Corn** - https://www.wowhead.com/quest=38647/for-the-corn
As well as without completing the other quests you can still accept and complete the last quest of this chain.
Quest - **Shriek No More** - https://www.wowhead.com/quest=39117/shriek-no-more
Proof:
https://imgur.com/5MN2y7z

_**Storyline Black Rook Hold:**_
https://www.wowhead.com/quest=38691/jarods-mission
The NPC does not give you the first quest of the storyline.
Proof:
https://imgur.com/g4jmzEx
Due to this issue the whole storyline is affected, cannot be completed.

Side quests are also not appearing.

**Comment by Thale94** [comment]
Quest - The Corruptor - (id 39384) after i kill the npc "Kagraxxis the Corruptor" i can't turn in the quest (after abandoning the quest and adding it back it worked)
https://imgur.com/a/kuktuhe
Solid as a Rock - (id 38235) The quest is Auto-Complete but tho is not showing is completed on the screen only when i check on npc
https://imgur.com/a/n3w4S8o
Death to the Witchmother - (id 38225) Same issue as the previous quest "Auto-Complete"
https://imgur.com/a/HWUjgIq
Entangled Dreams - (id 38147) Can't turn in the quest (after abandon and re-adding it, it worked)
https://imgur.com/a/NQy3ckE
Malfurion's Fury - (id 38595) Npc Missing (added the quest manually but can't complete it because Npc Ysera is missing
https://imgur.com/a/8cb4lYy
The Demon's Trail - (id 38753) Cinematic not playing, the screen remains black and nothing happens (can skip the cinematic tho)
Close Enough to Touch - (id 41763) Quest is auto-complete but not showing it as complete, this is the reason why is not working (going straight where you should turn in the quest, you can just turn it in and continue)
https://imgur.com/a/UoVN6Ty
A Village in Peril - (id 38643) i can take the quest from both Npc's the one next to Elune Temple and the one next to the Overturned Cart and you can have the quest twice in your quest log
https://imgur.com/a/tjaOR7X
https://imgur.com/a/d5XafQ8
https://imgur.com/a/IzAxSYq
For the Corn! - this quest should be after the quest "A Sight For Sore" but the order is reversed
The Warden's Signet - Npc "Lelyn Swiftshadow" is not dropping the Warden's Signet / unable to start quest without it (killed her like 5/6 times)
https://imgur.com/a/4Bfg6YC

**Comment by FiuryMan** [comment]
Fixed.
