### ISSUE TITLE
Druid Class Hall Campaign

### ISSUE THREAD

**Issue by Chazier1** [Evolution-WoW/Bug-Report#930]
**Quest: To the Dreamgrove ID: 40645 ** Link : https://www.wowhead.com/quest=40645/to-the-dreamgrove
Quest is doable however, totally not how its supposed to be. After completing the ritual on the previous quest "The Dreamway" there is a green portal supposed to spawn at the location. However due to that not appearing you cannot complete the scene as in the video below

Proof of fault: https://imgur.com/xlJSRkI
How it's supposed to be: https://www.youtube.com/watch?v=02fx5kWO2f4
                   Picture: https://imgur.com/undefined
Quest was completed using the learnt ability "Dreamwalk" 

Doable up to the "Weapons of Legend" which is where supposedly you get your artifact weapon, however upon completion, you are supposed to grab the next quest " Sowing the Seed" from the same NPC, but it is missing. Further quests in the campaign are not doable due to this. 

**Quest : Weapons of Legends ID : 40646**  Link : https://www.wowhead.com/quest=40646/weapons-of-legend

Affected quests : 

**Quest: Sowing the Seed ID : 41255**    Link: https://www.wowhead.com/quest=41255/sowing-the-seed

**Quest: Ascending the Circle ID : 41332**  Link : https://www.wowhead.com/quest=41332/ascending-the-circle

**Quest: Word on the Winds ID : 40652**   Link : https://www.wowhead.com/quest=40652/word-on-the-winds

**Quest: Making Traits ID : 40653**  Link : https://www.wowhead.com/quest=40653/making-trails

**Comment by FiuryMan** [comment]
>**Quest: To the Dreamgrove ID: 40645 ** Link : https://www.wowhead.com/quest=40645/to-the-dreamgrove
Quest is doable however, totally not how its supposed to be. After completing the ritual on the previous quest "The Dreamway" there is a green portal supposed to spawn at the location. However due to that not appearing you cannot complete the scene as in the video below

>Proof of fault: https://imgur.com/xlJSRkI
How it's supposed to be: https://www.youtube.com/watch?v=02fx5kWO2f4
Picture: https://imgur.com/undefined
Quest was completed using the learnt ability "Dreamwalk"

Quest working. The scenario is disabled and upon accepting the quest you get insta teleported to Class hall. Nothing to fix here.

>Quest : Weapons of Legends ID : 40646 Link : https://www.wowhead.com/quest=40646/weapons-of-legend

Quest working. Auto-Complete.

>quest " Sowing the Seed" from the same NPC, but it is missing. Further quests in the campaign are not doable due to this.

Fixed.
