### ISSUE TITLE
Druid Class Hall Campaign 

### ISSUE THREAD

**Issue by Malefique96** [Evolution-WoW/Bug-Report#936]
Quest ''Cleaning Up'' -  is not working as he should, it takes time to complete because is not working as it should. https://imgur.com/6lla38g     
How it should work ? 29:40 https://www.youtube.com/watch?v=NCycBPkbl7Q
 
Quest ''Branching Out'' - you can't choose the class hall upgrade.   https://imgur.com/3ZuHP5A 
How it should work ? - https://www.youtube.com/watch?v=uwcM7nOIW9o

**Comment by Chazier1** [comment]
Basically i completed the quest "Making traits ID: 40653" with the command as i had no resources, but after giving in the quest, , i could not get the next one "Growing Power" from the NPC "Archdruid Hamuul Runetotem"
Proof: https://imgur.com/8PUOwnU
I had to take the quest through the command.

**Quest: Rise Champions ID : 42583**  https://www.wowhead.com/quest=42583/rise-champions
Recruiting Naralex worked just fine, however going into the cave to recruit Zen'Tabra didn t go well, i cannot interact with the NPC
Proof: https://imgur.com/tlgf08K
Tried to abandon the quest and take it again, however this time it didn t even let me get Naralex(Note: The first time i did the quest, he had a exclamation mark above his head which was like sort of taking and giving in a quest from him to count the objective, whereas the other one didn't, and i've checked and this is how it's supposed to be)
Links: https://www.wowhead.com/quest=40650/champion-zentabra
           https://www.wowhead.com/quest=42096/champion-naralex
**Quest: Breaching Out**
For me it worked just fine and i have also lvld up my char with the command.

**Quest: The protectors ID: 43991**  Link: https://www.wowhead.com/quest=43991/the-protectors
Not that it's bugged, but from what i remember and also checked, you had to use specific spec spells(stealth-feral, regrowth- resto and so on) near the stones to complete the objective for the specific affinity, feral guardian restoration and balance, however here was just pressing on the stone. If the goal is to just shorten the quest and to make it easier just ignore this, thought of mentioning just in case. 

Some NPC's seem to be phasing in and out depending on how far you get from them, for example when i'm near they appear, however as soon as i get a small distance in between me and them they phase out.
Proof : https://imgur.com/isTtHsX
            https://imgur.com/W7R8siR
Note: Again, if intended, my apologies and please ignore

**Quest: Teensy Weensies!**
The quest is working however, the nightmares from the previous quest that takes place in the same location did not disappear, from what i saw on different sources, after being killed they become like some sort of "blood pool"
Proof: https://imgur.com/undefined
 This is an example of how it should be: https://www.youtube.com/watch?v=SY-S2c68or4 ( 0:30 - )

Also, when using the quest item on one dragon, it spawns another one instead of having to go from one to another, isn't really a bad thing as it makes a quest a bit easier to complete, but worth notifying.

**Quest: Cleaning up ID: 42043** Link  https://www.wowhead.com/quest=42043/cleaning-up
Instead of blood pools there are these imense purple flames, where you just sit in them and the objectives goes up 1 by 1 aprox every 1-2 seconds, sometimes faster, whereas they are supposed to be presented as red pools.
Proof: https://imgur.com/Q0eDROi
How it's supposed to be : https://imgur.com/93wqaAi

**Quest: Communing With Malorne**
Nothing very important here, but the indications on where to go, on map and on the mini-map are missing.

**Quest: A New Beginning ID: 42046 ** Link : https://www.wowhead.com/quest=42046/a-new-beginning
After completing the previous quest "Communing with Malorne", Remulos did not give me the quest and had to take it through the command.
However, i was able to recruit the two champions: Hamuul and Mylune without having to take the main quest first. Other than that, quest works fine.

**Quest: Enter Nightmare ID: 42051 **  Link https://www.wowhead.com/quest=42051/enter-nightmare
I had to add the quest with the command as Rensar Greathoof wasn't giving it, neither the quest helper. 

**Quest: Archimonde the Defiler ID: 42054** https://www.wowhead.com/quest=42054/archimonde-the-defiler
Just something worth checking, it just seemed not doable for a 811 ilvl druid, his dmg + the fall dmg from the mechanics seemed pretty high, and in order to do it i had to use a hp command so that i wouldn t die.

Rest of the quests worked fine, not exactly blizzlike as some interactions were slightly off, but nothing that have would've affected doing them.
